### ISSUE TITLE
Arbitrary Ordering of Libraries and Languages

### ISSUE THREAD

**Issue by MingweiSamuel** [WxWatch/riot-api-libraries#11]
The languages are in alphabetical order which seems pretty arbitrary. Doesn't really matter though. More importantly, libraries seem to be in an arbitrary order (seems like by the .json timestamp right now). Would make sense to order them by stars maybe.

**Comment by WxWatch** [comment]
https://discussion.developer.riotgames.com/articles/61/public-libraries-for-the-riot-games-api.html

They're ordered by `most recent commit`

**Comment by MingweiSamuel** [comment]
Ah, makes sense. Didn't notice the "last updated" was in ascending order.
