### ISSUE TITLE
Add librairie Pyke

### ISSUE THREAD

**Issue by systeme-cardinal** [WxWatch/riot-api-libraries#67]
Hi 

I create a librairie NodeJs for RiotAPI and DDragon.
So I submit my application : 
github: https://github.com/systeme-cardinal/node-Pyke
npm: https://www.npmjs.com/package/pyke

Riot APi is cover a 90%
DDragon is cover a 20% (for API DDragon, I used Static Data V3)

**Comment by raitono** [comment]
You can submit a pull request to include your library, check the readme.
https://github.com/WxWatch/riot-api-libraries#i-want-to-include-my-library

> I Want to Include My Library!
> Awesome! Simply create a Pull Request that adds a file with your library's configuration to the appropriate folder (if your language's folder isn't there, feel free to create it!). Once we verify that everything is correct, we'll merge it in and you're all set!
