### ISSUE TITLE
v3 APIs

### ISSUE THREAD

**Issue by WxWatch** [WxWatch/riot-api-libraries#8]
On July 24, all APIs that are not `v3` will be turned off. Consequently, there will probably be a large number of 3rd party libraries that won't get updates for this and will, effectively, be useless to the community. 

The libraries article is likely going to want to hide these libraries or deprioritize them to a "Deprecated" section of the article. 

To do this, there needs to be a way for developers to indicate that their library supports v3 APIs. That way, even if they don't get updated until after the deprecation window is up, they can still update the config here and "restore their status" on the main libraries article.

**Comment by WxWatch** [comment]
I don't really want to have a hard-coded `v3` flag, as I'd rather have a system that can be extended into the future for other things (rate limiters, tournament API support, specific APIs support, etc.).

July 24 is plenty of time to get a good solution in place but in the event that doesn't happen, a stop-gap temporary flag may be necessary.

Maybe something like:
```
"supportedApis": [
  "summoner-v3",
  "match-v3",
  "matchlist-v2.2"
]
```

OR
```
"supportedApis": {
  "summoner": 3,
  "match": 3
  "matchlist": 2.2
}
```

**Comment by MingweiSamuel** [comment]
Voting for the first way because Rito's naming tends to drift... `championmastery` became `champion-mastery-v3` and `runes-masteries-v1.4` became `runes-v3` and `masteries-v3`

**Comment by msx752** [comment]
@WxWatch i created a c# .netcore library for v3 apis, (using fluent api and version specific api and also after developing generate apiClass automatically) but i dont use json export like your example (Linq can be used for my project)
example FluentApi: https://github.com/msx752/RiotGamesApi.AspNetCore/blob/master/RiotCaller.AspNetCore/Extensions/Extension2.cs

sample auto generated apiClass(using FluentApi) : https://github.com/msx752/RiotGamesApi.AspNetCore/blob/master/RiotCaller.AspNetCore/Api.cs

is it useful or Should I change structure ?

**Comment by WxWatch** [comment]
Added a tagging system for the v3 issue

Closing.
